baseURL: "https://erlingrj.github.io"
title: Erling Rennemo Jellum
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
  main:
      - name: Projects
        url: /projects/
        weight: 1

params:
    description: "I am a PhD candidate at the Norwegian University of Science and Technology working on hardware and software systems for real-time computing"
    author: Erling Rennemo Jellum
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          subtitle: "I am a researcher and engineer working on real-time software and hardware."
          title: Erling Rennemo Jellum
          imageUrl: "/picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Erling Rennemo Jellum
          buttons:
            - name: Projects
              url: /projects
    socialIcons:
        - name: Email
          url: mailto:erling@duck.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=00W_DgkAAAAJ&hl=no
        - name: GitHub
          url: https://github.com/erlingrj?tab=repositories

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Erling Rennemo Jellum"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
